version: "3.1"

services:
  # services
  # profiles microservice
  profiles:
    container_name: ms_profiles
    build:
      context: ./profiles/docker
    volumes:
      - ./profiles:/var/www
      - ./storage/app/profiles:/var/www/storage/app
      - ./storage/logs/profiles:/var/www/storage/logs
    restart: unless-stopped
    ports:
      - 8001:80
    networks:
      - app-network

  # php project
  php-project:
    container_name: php-project
    build:
      context: ./application/docker
    volumes:
      - ./application:/var/www
      - ./storage/app/application:/var/www/storage/app
      - ./storage/logs/application:/var/www/storage/logs
    restart: unless-stopped
    ports:
      - 8002:80
    networks:
      - app-network

  # countries
  countries:
    container_name: ms_countries
    build:
      context: ./countries/docker
    volumes:
      - ./countries:/var/www
      - ./storage/app/countries:/var/www/storage/app
      - ./storage/logs/countries:/var/www/storage/logs
    restart: unless-stopped
    ports:
      - 8003:80
    networks:
      - app-network
  
  # countries
  cities:
    container_name: ms_cities
    build:
      context: ./cities/docker
    volumes:
      - ./cities:/var/www
      - ./storage/app/cities:/var/www/storage/app
      - ./storage/logs/cities:/var/www/storage/logs
    restart: unless-stopped
    ports:
      - 8004:80
    networks:
      - app-network

  # frontend trial
  frontend:
    container_name: ms_frontend
    build:
      context: ./frontend
    ports:
      - 8000:3000
      - 49153:49153
    expose:
      - "49153"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    networks:
      - app-network

  # databases
  # mongodb service
  mongo-database:
    container_name: mongo-database
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    env_file:
      - ./config/db.env
    ports:
      - 27017:27017
    networks:
      app-network:
        aliases:
          - mongo-db
            
  # sql db
  sql-database:
    container_name: sql-database
    image: mysql:5.7
    env_file:
      - ./config/db.env
    volumes:
      - sqldb_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - app-network

# volumes
volumes:
  sqldb_data:
    driver: local
  mongodb_data:
    driver: local

# networks
networks:
  app-network:
    driver: bridge
